### ISSUE TITLE
json output bug

### ISSUE THREAD

**Issue by seoanezonjic** [TheJacksonLaboratory/LIRICAL#620]
When the RC2 version is set with output json, if the phenopacket has not age data (I think that with sex data could occur the same) lirical breaks with:
`12:59:18.044 [main] ERROR o.m.l.c.c.AbstractPrioritizeCommand - Error: Cannot invoke  org.monarchinitiative.lirical.core.model.Age.equals(Object)" because the return value of  org.monarchinitiative.lirical.core.analysis.AnalysisData.age()" is null`
However, if the json output is not requested there is no error. I think that age or sex data should be NOT mandatory to json output. In my case I lack of this data with the HPO profiles that I'm analysing.
Thank you in advance

**Comment by ielis** [comment]
Hi, thanks for reporting the bug. As you suggested, there was an issue in the JSON writer which expected the age to always be non-null. However, the age field can be `null` based on the `AnalysisData` contract.

I fixed the bug in #621 and the updated code is available in the *latest* LIRICAL.

I will close this since it is very likely that #620 fixed the error. However, please feel free to reopen if the error persists.

**Comment by seoanezonjic** [comment]
Hi @ielis 
I've enabled again the json output and I've realised that my version was old so  I've followed the link https://thejacksonlaboratory.github.io/LIRICAL/latest/setup.html
The documentation describes a RC3 version but when I go to releases or I compile the code following the instructions, I get a RC2 jar file and the error described in this issue persists.
What am I doing wrong?
